### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by haudren** [stephane-caron/pymanoid#12]
Do you have any plans to support python3 ? It could be nice to use `async` to have asynchronous control/simulation processes. Morevoer [support for python2 will be dropped by 2020](http://www.python3statement.org/).

For compatibility purposes, I think that most of the current problems (I ran 2to3) can be fixed and used in both versions by importing `__future__`:
- `print` is a function, and thus needs parentheses around the message
- `xrange`, `itervalues` and so on have been renamed to `range`, `values`
- Relative imports must start with a dot i.e. `from .ik import IKSolver`

Oh well, I just saw that `openrave` does not support Python3 yet :crying_cat_face:

**Comment by stephane-caron** [comment]
Thanks for your comment! Indeed the first thing will be for OpenRAVE to support Python3. Meanwhile,
- As of 1d7854d8d8b3dea057b6db52d9eb63def3546440 pymanoid calls `print` as a function
- As of d9b804d38fe32f4cbc0564059124c4c341827308 it uses leading periods for relative imports
- But... `xrange` will stay `xrange` because it is faster than `range` in Python2. Sure, the speedup only appears for large lists, but I don't want to introduce extraneous thinking here. It will always be easy to switch to `range` when Python3's time has come :wink:
