### ISSUE TITLE
MinVelocityTask is not found.

### ISSUE THREAD

**Issue by PAlamirpour** [stephane-caron/pymanoid#16]
Hello sir.
I have been working on pymanoid. I realized which there is not MinVelocityTask under pymanoid.tasks class. Would you help me out for fixing the problem?

**Comment by stephane-caron** [comment]
This class is now called [MinVelTask](https://scaron.info/doc/pymanoid/inverse-kinematics.html#pymanoid.tasks.MinVelTask).

Maybe your reference to ``MinVelocityTask`` comes from code written for a older version of pymanoid?

**Comment by PAlamirpour** [comment]
`MinVelocityTask` was used in [topp-mpc](https://github.com/stephane-caron/topp-mpc). So it seems it should be edited.

I appreciate your time and effort.

**Comment by stephane-caron** [comment]
I see. Indeed topp-mpc relies on an older version of pymanoid: if you look at the pymanoid submodule there, you will see that it imports commit ``3f8a5c6``.

To use it, make sure you clone it with ``git clone --recursive`` so that the proper pymanoid submodule is fetched as well (if you did not, go to the topp-mpc folder and run ``git submodule update --init``). Then, run the main script ``./walk.py`` from the topp-mpc folder. It will then use its local pymanoid version (with ``MinVelocityTask``) rather than the more recent one installed on your system (with ``MinVelTask``).

Actually, I had forgotten to specify in the topp-mpc README that the git clone should be ``--recursive``. This is now fixed. Thanks for reporting this!

Using submodules this way ensures that older projects keep working even after pymanoid evolves. I will gladly accept PRs that update pymanoid submodules of these projects to more recent versions.
