### ISSUE TITLE
Heel-strike toe-off motion with the biped

### ISSUE THREAD

**Issue by mohamadmahdavian** [stephane-caron/pymanoid#19]
Hi Dr.Caron

Thanks to you I was able to generate motion for our biped robot in a straight path. I have uploaded the video file for you. I have another question. Is there anywhere in your code for defining heel-strike toe-off motion for the robot to make it more human-like? 

Thank You

**Comment by stephane-caron** [comment]
Nice job!

There is no pre-defined heel-strike or toe-off motions in pymanoid, you will have to generate them _e.g._ by directly pitching your foot ankle frame.

Also I see that you are using the linear swing foot trajectories from the `multi_contact_walking.py` example. Those found in [swing_foot_control.py](https://github.com/stephane-caron/fip-walking/blob/master/wpg/swing_foot_control.py) of the [fip-walking](https://github.com/stephane-caron/fip-walking/) project are better:

![image](https://user-images.githubusercontent.com/1189580/51736545-a0641500-208a-11e9-92b4-fcda3700553a.png)

Sorry for not integrating those back into pymanoid yet. Feel free to open a PR if you do it in your work and I will gladly review/merge it so that others can benefit from it as well.

**Comment by mohamadmahdavian** [comment]
Thank You Dr.Caron. I will try to use your recommended gait motion .Also, if I developed the Heel-Strike toe-off motion I will try to send it to you.
