### ISSUE TITLE
Walking parameters and simulation "dt"

### ISSUE THREAD

**Issue by Ahmadreza-Shahrokhshahi** [stephane-caron/pymanoid#20]
Hi Dr. Caron,

1. I want to change (decrease) the walking speed of the robot in Pymanoid. Step length can be set in "generate_staircase", then by changing "ds_duration" and "ss_duration" the walking speed is determined. However, I cannot change the values much (for instance making them half), because it make the robot fall down. 
Could you please advise how can I have decrease the walking speed, and what parameters play role in balancing when changing the walking speed?
--------------------------
2. When I run the simulation for a certain number of steps the number of results for the forces, joint angles, etc. are twice (for example I run it with the command "sim.step(500)" it gives me 1000 data for each variable which I log) and it's weird to me!!
--------------------------
3. The other question is about the simulation time-step; is "dt" the real-time simulation time-step? (I think it is, because when I run the simulation for 500 time-steps with dt=0.03, it takes approximately 15 seconds to complete)-- What would be changed if I change the dt?

Thanks a lot

**Comment by stephane-caron** [comment]
### Question 1: Towards dynamic walking

If I follow correctly you are based on the [multi_contact_walking.py](https://github.com/stephane-caron/pymanoid/blob/master/examples/multi_contact_walking.py) example. The walking pattern generator in this example is based on a safe but conservative contact-stability criterion (explained in [this paper](https://hal.archives-ouvertes.fr/hal-01349880/document)), which is applicable to reasonable walking speeds but does not apply to more dynamic walking gaits.

When you reduce phase durations (e.g. halving them, which means doubling the walking speed) you are asking for a more dynamic gait, thus at some point the conservative criterion will not apply any more and the walking pattern generator will failt (→ the robot falls down).

For dynamic walking pattern generation, you can take a look at [fip-walking](https://github.com/stephane-caron/fip-walking) or [capture-walking](https://github.com/stephane-caron/capture-walking-pattern-generation). In my experience it is more difficult to make the former run real-time because of numerical issues. The latter is my latest work where we have addressed these with a faster custom solver. It can generate dynamic walking such as in [this video](https://scaron.info/videos/capture-walking.mp4).

### Question 2: Logging data

This must be related to the way you log data. In the example, I log computation times by appending a time measurement at every simulation tick, and you can check that after 200 iterations there are exactly 200 logged items:

```
In [1]: sim.step(200)

In [2]: sim.print_comp_times()
          IKSolver: 7.43 +/- 2.10 ms (max: 21.34 ms, min: 5.97 ms, 200 items)
          qp_build: 0.27 +/- 0.09 ms (max: 0.74 ms, min: 0.21 ms, 198 items)
          qp_solve: 0.34 +/- 0.24 ms (max: 1.56 ms, min: 0.15 ms, 198 items)
qp_solve_and_build: 0.61 +/- 0.29 ms (max: 2.26 ms, min: 0.36 ms, 198 items)
    tube_dual_hrep: 0.18 +/- 0.09 ms (max: 0.86 ms, min: 0.08 ms, 198 items)
    tube_dual_vrep: 5.35 +/- 3.18 ms (max: 21.26 ms, min: 1.10 ms, 198 items)
  tube_primal_hrep: 0.15 +/- 0.05 ms (max: 0.37 ms, min: 0.11 ms, 198 items)
  tube_primal_vrep: 0.16 +/- 0.21 ms (max: 2.95 ms, min: 0.08 ms, 198 items)
```

Take a look at [sim.py](https://github.com/stephane-caron/pymanoid/blob/master/pymanoid/sim.py) to see how the ``comp_times`` dictionary is updated.

### Question 3: Simulation timestep

That's right, ``dt`` is the simulation time step. I just completed [the documentation](https://scaron.info/doc/pymanoid/simulation-environment.html#Simulation.dt) with more details on it:

```
    Attributes
    ----------
    dt : scalar, optional
        Simulation timestep, that is, time interval between two ticks in
        simulation time. The default value of 30 [ms] is chosen so that stock
        simulations run real-time on modern computers. Lower simulation steps
        make forward integration more precise, but will result in loss of
        real-timeness at some point (a simulation runs real-time when the
        computer spends less than ``dt`` to carry out all computations at every
        tick, so that it takes N seconds of real time to simulate N seconds of
        simulation time).
```

Thanks for your feedback!

**Comment by Ahmadreza-Shahrokhshahi** [comment]
Thanks for your response.
Questions 1 and 3 are clear for me now, but I could not resolve the Question 2.

**Comment by stephane-caron** [comment]
Here is a wrench logger class that you can add to the [multi-contact walking](https://github.com/stephane-caron/pymanoid/blob/master/examples/multi_contact_walking.py) example:
```python
class WrenchLogger(pymanoid.Process):

    def __init__(self, wrench_drawer):
        self.drawer = wrench_drawer
        self.wrenches = []
        super(WrenchLogger, self).__init__()

    def on_tick(self, sim):
        self.wrenches.append(self.drawer.find_supporting_wrenches(sim))
```
Schedule it in your simulation (after the other processes) by:
```python
    wrench_logger = WrenchLogger(wrench_drawer)
    sim.schedule_extra(wrench_logger)
```
After 100 simulation steps, you will find that it has logged the 100 wrench samples for each step:
```python
In [1]: sim.step(100)

In [2]: len(wrench_logger.wrenches)
Out[2]: 100
```
This logger class is just a simple example. Note that it is inefficient as it recomputes wrenches a second time by calling the drawer function.
