### ISSUE TITLE
DOF Acceleration Limits

### ISSUE THREAD

**Issue by Ahmadreza-Shahrokhshahi** [stephane-caron/pymanoid#22]
Hi Dr. Caron,
As there are limits for the DOFs velocities,  I wanted to make some constraints for the acceleration too. I found the openRAVE command for setting and getting DOFs limits (SetDOFAccelerationLimits and GetDOFAccelerationLimits respectively). For the velocity limits, a variable is created (qd_lim) in the code "robot.py", and is used in"ik.py". I was wondering if we could do something similar based on the method that is used in the Pymanoid? 

Thnaks

**Comment by stephane-caron** [comment]
Acceleration limits are not implemented yet, but they can be easily added to the IK in [build_qp_matrices](https://github.com/stephane-caron/pymanoid/blob/c0f17db6d8b7f3028b9d4b72e16c2691e93ef295/pymanoid/ik.py#L259). The derivation is:
```
                qdd <= qdd_max
(qd - self.qd) / dt <= qdd_max
                 qd <= self.qd + qdd_max * dt
```
Thus you get a ``qd_max_accel``, and similarly a ``qd_min_accel``. The return value of ``qd_max`` is the minimum of this new limit with the two other ones, and similarly for ``qd_min``.

You can implement this and open a PR. Otherwise I will do it, but it will take some time.

**Comment by Ahmadreza-Shahrokhshahi** [comment]
Thanks a lot, I have made some changes in the code. The point is that I should have make changes in the "solve" as well, in order to ignore the DOF relaxing phase in the minimization.

**Comment by stephane-caron** [comment]
Actually the solution is not that simple! Thank you very much for opening this issue :)

Implementing acceleration limits straightforwardly as I described above does not work well. That is, it works locally, but if IK targets move fast you easily end up with unfeasible QP constraints (because position and acceleration bounds cross each other). This problem is well-known in the literature.

I implemented in 4c6eac2d492854af17f17985be4eea46bf3dd645 the solution from Equation (14) of [Control of Redundant Robots Under Hard Joint Constraints: Saturation in the Null Space](http://ieeexplore.ieee.org/document/7097068/) by Flacco _et al._, which adds a second inequality to the previous one:
```
                 qd <= self.qd + qdd_max * dt
                 qd <= sqrt(2 * self.qdd_lim * (self.q_max - q))
```
I tested it and it seems to work well in practice (I don't get unfeasible problems even when task targets move fast).

**Conclusion:** you can now set the joint acceleration limits of your robot in ``robot.qdd_lim``.

**Comment by mohamadmahdavian** [comment]
Hello Dr.Caron

Thank you for this update. As you said it limits the angular acceleration. But if I decrease the step time(dt=0.01 sec) it can not find any solutions. Is there anyway to have the limits such that it adjusts the motion for different settings? 

Thank You

**Comment by stephane-caron** [comment]
Thanks for catching this bug!

It was a sign error occurring when acceleration limits were saturated with targets far from feasible (i.e. large task errors). It is now fixed.

**Comment by mohamadmahdavian** [comment]
Thank you for the update.I think it solved the problem.
