### ISSUE TITLE
Calculating joint forces (internal forces)

### ISSUE THREAD

**Issue by mohamadmahdavian** [stephane-caron/pymanoid#25]
Hello Dr.Caron

I hope you are doing well. I was able to calculate joint torques using compute_inverse_dynamics and I verified my results with other methods as well. But I need joints internal forces as well and I couldn't find any functions for it in pymanoid or openrave.Is there any simple functions for this matter? Also, I know I can calculate it for joints one by one, buy it doesn't make sense to write down a code for a robot model and when the model changes i wouldn't be able to use it. I need to have a general code. Is there anyway to have internal forces using available functions in pymanoid?

Thank You
Regards

**Comment by stephane-caron** [comment]
Can you detail what you mean by "joint internal forces" and how they differ from joint torques?

**Comment by mohamadmahdavian** [comment]
Using inverse dynamics I only can find torque in one direction. But I need to find 3 axes of forces and 3 axes of torques in each joint. Something similar to output of Newton-Euler method. Is there anyway to have these values without using newton-Euler method?

Thank You

**Comment by stephane-caron** [comment]
I see. That's an interesting question and I don't know the answer yet. Have you searched in textbooks such as Roy Featherstone's _Rigid Body Dynamics Algorithms_?

@jcarpent: would you have some suggestions here?

**Comment by jcarpent** [comment]
@mohamadmahdavian 
You can get access to this informations in Pinocchio (https://github.com/stack-of-tasks/pinocchio).
If you use **RNEA**, you can get access to this information in `data.f`. 
To install it, you can follow: https://stack-of-tasks.github.io/pinocchio/download.html

**Comment by stephane-caron** [comment]
OK that's one way to answer :sweat_smile: But here OpenRAVE already did the RNEA, so for a quick fix I was wondering: is there a way to compute the wrench of link A on link B (internal force) given the vector of joint torques computed by RNEA, and any of the usual matrices (link Jacobians, link inertias, etc.)?

**Comment by jcarpent** [comment]
Not really. The torque is only the projection of the wrench applied on a given link onto the Joint axis.
So, if internally, you cannot get an access to the wrench of forces for each joint, then it is impossible to retrieve this information.

**Comment by stephane-caron** [comment]
OK I see, thanks!

@mohamadmahdavian as it turns out OpenRAVE does compute what you are looking for in its RNEA, but it is not exporting these values to the Python interface (and as @jcarpent points out there is no easy way for us to recover that information afterwards).

What you can do then is a small patch to OpenRAVE by:
- Going to [kinbody.h](https://github.com/rdiankov/openrave/blob/master/include/openrave/kinbody.h) and [kinbody.cpp](https://github.com/rdiankov/openrave/blob/master/src/libopenrave/kinbody.cpp)
- Making ``vLinkForceTorques`` a member array of the ``KinBody`` class rather than a local variable (similar to ``vLinkTransforms`` and ``vLinkVelocities``)
- Exporting this new member to Python as ``GetLinkForceTorques()`` (similar to ``GetLinkTransformations()`` and ``GetLinkVelocities()``)

**Comment by stephane-caron** [comment]
Closing this issue as it turns out to be OpenRAVE-related. You can ask follow-up questions in the [OpenRAVE issue tracker](https://github.com/rdiankov/openrave/issues).
