### ISSUE TITLE
Jerk Limitation

### ISSUE THREAD

**Issue by mohamadmahdavian** [stephane-caron/pymanoid#26]
Hi Dr.Caron

I am trying to use pymanoid generated data on an actual motor. I have angular velocity and angular acceleration limits in the code based on motor's specification. But when we run the motor,it sometimes stops working on the points that we have big amount of change in the angular acceleration. We have checked everything in the board side and we have consulted with some experts. They mentioned that the differentiation of acceleration which is Jerk of the system is too high and that is the reason that the motor doesn't work. I think it is a necessary feature to add. Do you have any idea how we can add it? Do you think it would be better to consider it as another constrain or add it to goal function and minimize it in the solver? Also Do you think it would be better to have the constrain for the jerk of DoFs or the jerk of COM?

Thank You

**Comment by stephane-caron** [comment]
> Do you have any idea how we can add it? Do you think it would be better to consider it as another constrain or add it to goal function and minimize it in the solver?

The current IK was initially implemented having constant-velocity steps in mind. Recently we added acceleration limits the easy way, by storing the current velocity and minimizing the difference between the next velocity and the current one (equiv. to acceleration under fixed time step). The same idea can be applied to jerk: store the current acceleration, and minimize the difference between the next one and the current one.

However, this sequence of small-step extensions is accumulating [technical debt](https://en.wikipedia.org/wiki/Technical_debt). A better solution in the long-term would be to implement an acceleration-based QP (i.e. constant-acceleration steps rather than constant-velocity ones), or even a jerk-based QP. This is not so hard to do, but it takes work to both implement it and test it in many different situations.

Doing so would make the IK act as a smoother filter. But maybe before that you want to check that your targets themselves are smooth (see below).

> Also Do you think it would be better to have the constrain for the jerk of DoFs or the jerk of COM?

Here you are pointing to something important. Smoothness is desirable in general for control. But then, the first thing to get smooth IK outputs is to make sure that all your targets are smooth, and feasible (or close to feasible). If you want jerk-level smoothness while walking, then your foot and CoM targets should be jerk-smooth as well (_e.g._ vary with piecewise constant jerk).

Is that the case already? If not, making them smoother (and leaving the IK as is) might be the first thing you want to try.

**Comment by mohamadmahdavian** [comment]
Thank You Dr.Caron for your respond. We are working on your suggestions and I will let you know about the results.

**Comment by stephane-caron** [comment]
OK no problem. I'll be closing the issue for now, feel free to re-open it to resume the discussion.

**Comment by mohamadmahdavian** [comment]
Hi Dr.Caron

I hope you are doing well. I am trying to limit the jerk while solving the IK which can help us to have a better motion. I have added some lines to my IK code and the __build_qp_matrices function is now such this:

    def __build_qp_matrices(self, dt):
        """
        Build matrices of the quatratic program.

        Parameters
        ----------
        dt : scalar
            Time step in [s].

        Returns
        -------
        P : (n, n) array
            Positive semi-definite cost matrix.
        q : array
            Cost vector.
        qd_max : array
            Maximum joint velocity vector.
        qd_min : array
            Minimum joint velocity vector.

        Notes
        -----
        When the robot model has joint acceleration limits, special care should
        be taken when computing the corresponding velocity bounds for the IK.
        In short, the robot now needs to avoid the velocity range where it (1)
        is not going to collide with a DOF limit in one iteration but (2)
        cannot brake fast enough to avoid a collision in the future due to
        acceleration limits. This function implements the solution to this
        problem described in Equation (14) of [Flacco15]_.
        """
        n = self.nb_active_dofs
        P = zeros((n, n))
        v = zeros(n)
        with self.__lock:
            for task in self.tasks.itervalues():
                J = task.jacobian()[:, self.active_dofs]
                r = task.residual(dt)
                mu = self.lm_damping * max(1e-3, dot(r, r))
                P += task.weight * (dot(J.T, J) + mu * eye(n))
                v += task.weight * dot(-r.T, J)
        q = self.robot.q[self.active_dofs]
        qd_max_doflim = (self.q_max - q) / dt
        qd_min_doflim = (self.q_min - q) / dt
        qd_max = minimum(+self.qd_lim, self.doflim_gain * qd_max_doflim)
        qd_min = maximum(-self.qd_lim, self.doflim_gain * qd_min_doflim)
        if self.qdd_lim is not None:  # straightforward acceleration bounds
            qd = self.robot.qd[self.active_dofs]
            qd_max_acc = qd + self.qdd_lim * dt
            qd_min_acc = qd - self.qdd_lim * dt
            qd_max = minimum(qd_max, qd_max_acc)
            qd_min = maximum(qd_min, qd_min_acc)            
        if self.qdd_lim is not None:  # DOF-limit acceleration bounds
            Delta_q_max = maximum(self.q_max - q, 1e-32)
            Delta_q_min = maximum(q - self.q_min, 1e-32)
            qd_max_doflim_acc = +sqrt(2 * self.qdd_lim * Delta_q_max)
            qd_min_doflim_acc = -sqrt(2 * self.qdd_lim * Delta_q_min)
            qd_max = minimum(qd_max, self.doflim_gain * qd_max_doflim_acc)
            qd_min = maximum(qd_min, self.doflim_gain * qd_min_doflim_acc)

###### I have added these lines
        if self.jerk_lim is not None:
            qd = self.robot.qd[self.active_dofs]
            qdd = self.qdd[self.active_dofs]
            qd_max_jerk = qd + qdd * dt + .5*self.jerk_lim * dt * dt
            qd_min_jerk = qd + qdd * dt - .5*self.jerk_lim * dt * dt
            qd_max = minimum(qd_max, qd_max_jerk)
            qd_min = maximum(qd_min, qd_min_jerk)            
################
        return (P, v, qd_max, qd_min)

I have also added this line to my main walking code:
    robot.jerk_lim = 1800 * ones(robot.q.shape)

But it actually doesn't work. When the jerk limit is less than (for example) 1800 for each DoF it can not solve it and when it is more than this, it is not effective. Do you have any suggestions?

Thank You

**Comment by stephane-caron** [comment]
The problem when you do this:
```python
    qd_max_jerk = qd + qdd * dt + .5*self.jerk_lim * dt * dt
```
is that these inequality constraints can get in conflict with the other ones (for position, velocity and acceleration limits). This is why your QP has no solution when this jerk limit is low.

As you can see above, the formula for the acceleration limit is
```python
    qd_max_doflim_acc = +sqrt(2 * self.qdd_lim * Delta_q_max)
```
rather than ``qd + qdd_max * dt``. This formula is consistent with the other limits. You can check out how it is derived in the following references:
- [Control of Redundant Robots Under Hard Joint Constraints: Saturation in the Null Space](https://ieeexplore.ieee.org/document/7097068) by Flacco _et al_.
- [Joint Position and Velocity Bounds in Discrete-TimeAcceleration/Torque Control of Robot Manipulators](https://hal.archives-ouvertes.fr/hal-01356989v3/document) by @andreadelprete

You should be able to follow the same reasoning to derive jerk limits. Once this is done, one last trick is to scale the resulting limit by ``doflim_gain`` (as done in the acceleration limit just above) to smooth out edge cases when hitting the limit.
