### ISSUE TITLE
Feature Request: manually selecting specific contact wrenches

### ISSUE THREAD

**Issue by ndehio** [stephane-caron/pymanoid#30]
As discussed today with @stephane-caron, I would like to have the opportunity to manually set a fixed wrench at a given robot link (not necessarily in rigid contact) and let Pymanoid select resulting wrenches only for the remaining contacts.
To my understanding, Pymanoid in its current state will always select resulting wrenches for all contacts.
Thanks!

**Comment by stephane-caron** [comment]
This is somehow related to #29. It requires a few changes in the code:

- Some way to specify whether a contact is "supporting" (current behavior, contact wrench found by optimization) or "managed" (desired behavior here: contact wrench is given).
- Maybe a shallow wrapper around [find_supporting_wrenches](https://scaron.info/doc/pymanoid/contact-stability.html#pymanoid.contact.ContactSet.find_supporting_wrenches) so that the user can pass managed wrenches as arguments.
- Alternatively, keep the current API and allow the user to set wrenches via the robot's [Stance](https://scaron.info/doc/pymanoid/inverse-kinematics.html?highlight=stance#stance).

I guess the second option is simpler. I'll look into it and keep you posted.

**Comment by stephane-caron** [comment]
Alright, here is a first version in the [external_force.py](https://github.com/stephane-caron/pymanoid/blob/master/examples/external_force.py) example. There is a small process that models an elastic hand contact with a wall. The meaningful part is that you can do:
```python
    stance.right_hand.set_wrench([0., 0., F_z, 0., 0., 0.])
```
When you set the wrench of a contact, it switches to "managed" mode (its color becomes blue to reflect this), meaning the user is now providing the contact wrench applied there. To go back to "supporting" mode (the default, contact is then red), use ``unset_wrench()``:
```python
    stance.right_hand.unset_wrench()
```
In this example, you can see the normal force increase as you move the blue right-hand contact inside the elastic wall frontier. Supporting wrenches under the feet are recomputed accordingly, and of course if the hand goes too deep into the wall the external force becomes so large it cannot be compensated by feasible foot wrenches:
![image](https://user-images.githubusercontent.com/1189580/65963809-ccc30300-e45b-11e9-902c-a157f90cfc58.png)
Let me know your thoughts!

**Comment by ndehio** [comment]
I noticed that when commanding a zero wrench with the new function
self.contact.set_wrench([0., 0., 0., 0., 0., 0.])
the entire robot becomes invisible for some reason...

So I will leave this issue open till this is solved.
