### ISSUE TITLE
Question Regarding MPC Controller Structure

### ISSUE THREAD

**Issue by mohamadmahdavian** [stephane-caron/pymanoid#34]
Hi Dr.Caron

I have been working on MPC controller which generates the motion for COM of the inverted pendulum. I have checked the codes and read some papers. First one was the one that you have referenced "Model Preview Control in Multi-Contact Motion– Application to a Humanoid Robot" for calculating phi,psi matrices. The structure of MPC controller in pymanoid is similar to this paper. Although, in that paper com jerk is not the goal function and in pymanoid the QP tries to minimize com jerk for generating motion of the COM.
My questions are:
1.In the X_goal variables of MPC linearization input why are you choosing Xd and Xdd and Yd and Ydd to be zero. Is it because we are making sure that robot can stop in 16 step times?
2.If I want to decrease the walking speed by increasing Tss and Tds(Tss=1.4s,Tds=1s) should I change the step number for MPC controller? Is it possible to make number of steps in MPC horizen(currently=16) dependent to velocity?
3. Is there any other paper which describes what you have done in MPC more similarly to pymanoid?

Also during our tests with pymanoid we concluded that we need to have ZMP reference and COM velocity as reference in the QP goal function for the MPC controller. My goal is to add ZMP reference and COM velocity reference to the goal function based on "[Online Walking Motion Generation with Automatic Footstep Placement](https://hal.inria.fr/inria-00391408v1/document)". Something similar to following equation:
![Screenshot from 2019-11-12 17-49-21](https://user-images.githubusercontent.com/32945083/68725996-03b92800-0575-11ea-8aea-41dbeaaedb7b.png)

4. Can you help me realize what changes do I need to make in the phi, psi,etc. matrices to include ZMP ref and COM velocity ref in goal function of MPC? Also, I don't need follow the COM position.

**Comment by stephane-caron** [comment]
Hi @mohamadmahdavian, these are many questions you are asking in this issue and it will take me a while to process it. For faster answers, ask only one question at a time and make it as precise as possible.

**Comment by stephane-caron** [comment]
Hi @mohamadmahdavian,

### 1. Choice of goal state

In the [LinearModelPredictiveControl](https://scaron.info/doc/pymanoid/walking-pattern-generation.html#linear-model-predictive-control) class, the target state ``x_goal`` can be anything. Here I assume you are referring to the particular choice ``x_goal = array([self.swing_target.x, 0., 0.])`` made in the [walking pattern generation tutorial](https://scaron.info/teaching/prototyping-a-walking-pattern-generator.html) (not part of pymanoid but a use case). In this case, yes, our terminal condition is that the robot stops at the end of the receding horizon. Note that this condition is a bit stronger than [what is currently done in the state of the art](https://scaron.info/teaching/capture-point.html).

### 2. Lowering the walking velocity

You can, but it might not be necessary. For [stair climbing](https://www.youtube.com/watch?v=vFCFKAunsYM) we use ``T_ss=1.4`` and ``T_ds=0.2``, keeping the same 1.6 [s] receding horizon.

The caveat to look out for here are discontinuous trajectories. When the last step in the horizon switches e.g. from DS to the next SS, your terminal condition jumps to the next footstep. If your receding horizon is too small, your MPC output might suddenly accelerate to catch up (best case), or the optimization problem might even not have a solution at all (worst case). The longer the horizon, the smaller the effect of this "back-fire" of the terminal condition onto your instantaneous control.

You can of course experiment with making the number of MPC steps dependent on the desired velocity. I haven't felt the need to do that so far, it might be interesting to try it out!

### 3. Paper related to the pattern generation tutorial

Yes, this tutorial is based on the paper [Trajectory Free Linear Model Predictive Control forStable Walking in the Presence of Strong Perturbations](https://hal.inria.fr/file/index/docid/390462/filename/Preview.pdf) by Pierre-Brice Wieber. It is linked at the beginning of the *Linear model predictive control* paragraph.

### 4. Implementing the variant with automatic footstep placement

You will need to update the [LinearModelPredictiveControl](https://scaron.info/doc/pymanoid/walking-pattern-generation.html#linear-model-predictive-control) class, specifically the *cumulated state error*:

- Currently it is computed with respect to a constant ``x_goal``, i.e. each term in the sum has the form ``|x_k - x_goal|``. You will need to replace this by a stacked vector of desired states: ``|x_k - v_k|``.
- Currently the state error is applied to the state directly, i.e. ``|x_k - x_goal|``. You will need to replace this by a matrix-vector form, i.e. ``|H * x_k + m - v_k|`` so that you can express the CoM velocity as ``xd_k = H_1 * x_k + m_1`` and similarly the ZMP as ``z_k = H_2 * x_k + m_2``. Here ``v_k`` will be respectively the target CoM velocity/ZMP.

Note that this more general API is already implemented in [copra](https://vsamy.github.io/en/blog/copra-example-python). Interfacing copra with pymanoid shouldn't be too hard: I would gladly merge a PR for that :slightly_smiling_face:
